// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: engine-vector-space-search-service.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WebStation int32

const (
	// 中华人民共和国财政部网站
	WebStation_MOFRPC WebStation = 0
)

// Enum value maps for WebStation.
var (
	WebStation_name = map[int32]string{
		0: "MOFRPC",
	}
	WebStation_value = map[string]int32{
		"MOFRPC": 0,
	}
)

func (x WebStation) Enum() *WebStation {
	p := new(WebStation)
	*p = x
	return p
}

func (x WebStation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebStation) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_vector_space_search_service_proto_enumTypes[0].Descriptor()
}

func (WebStation) Type() protoreflect.EnumType {
	return &file_engine_vector_space_search_service_proto_enumTypes[0]
}

func (x WebStation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebStation.Descriptor instead.
func (WebStation) EnumDescriptor() ([]byte, []int) {
	return file_engine_vector_space_search_service_proto_rawDescGZIP(), []int{0}
}

type DocType int32

const (
	// HTML格式文件
	DocType_HTMLDoc DocType = 0
	// TXT格式文件
	DocType_TextDoc DocType = 1
)

// Enum value maps for DocType.
var (
	DocType_name = map[int32]string{
		0: "HTMLDoc",
		1: "TextDoc",
	}
	DocType_value = map[string]int32{
		"HTMLDoc": 0,
		"TextDoc": 1,
	}
)

func (x DocType) Enum() *DocType {
	p := new(DocType)
	*p = x
	return p
}

func (x DocType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocType) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_vector_space_search_service_proto_enumTypes[1].Descriptor()
}

func (DocType) Type() protoreflect.EnumType {
	return &file_engine_vector_space_search_service_proto_enumTypes[1]
}

func (x DocType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocType.Descriptor instead.
func (DocType) EnumDescriptor() ([]byte, []int) {
	return file_engine_vector_space_search_service_proto_rawDescGZIP(), []int{1}
}

type PacketDeliveryStatus int32

const (
	// 数据包派送中
	PacketDeliveryStatus_InDelivery PacketDeliveryStatus = 0
	// 数据包派送完毕或无数据可供派送
	PacketDeliveryStatus_OutOfStock PacketDeliveryStatus = 1
)

// Enum value maps for PacketDeliveryStatus.
var (
	PacketDeliveryStatus_name = map[int32]string{
		0: "InDelivery",
		1: "OutOfStock",
	}
	PacketDeliveryStatus_value = map[string]int32{
		"InDelivery": 0,
		"OutOfStock": 1,
	}
)

func (x PacketDeliveryStatus) Enum() *PacketDeliveryStatus {
	p := new(PacketDeliveryStatus)
	*p = x
	return p
}

func (x PacketDeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketDeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_vector_space_search_service_proto_enumTypes[2].Descriptor()
}

func (PacketDeliveryStatus) Type() protoreflect.EnumType {
	return &file_engine_vector_space_search_service_proto_enumTypes[2]
}

func (x PacketDeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketDeliveryStatus.Descriptor instead.
func (PacketDeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_engine_vector_space_search_service_proto_rawDescGZIP(), []int{2}
}

// 传输数据包.
type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WebStation     WebStation           `protobuf:"varint,1,opt,name=web_station,json=webStation,proto3,enum=amazingchow.engine_vector_space_search_service.WebStation" json:"web_station,omitempty"`
	DocType        DocType              `protobuf:"varint,2,opt,name=doc_type,json=docType,proto3,enum=amazingchow.engine_vector_space_search_service.DocType" json:"doc_type,omitempty"`
	DocId          string               `protobuf:"bytes,3,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	DocTitle       string               `protobuf:"bytes,4,opt,name=doc_title,json=docTitle,proto3" json:"doc_title,omitempty"`
	DeliveryStatus PacketDeliveryStatus `protobuf:"varint,5,opt,name=delivery_status,json=deliveryStatus,proto3,enum=amazingchow.engine_vector_space_search_service.PacketDeliveryStatus" json:"delivery_status,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_vector_space_search_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_engine_vector_space_search_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_engine_vector_space_search_service_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetWebStation() WebStation {
	if x != nil {
		return x.WebStation
	}
	return WebStation_MOFRPC
}

func (x *Packet) GetDocType() DocType {
	if x != nil {
		return x.DocType
	}
	return DocType_HTMLDoc
}

func (x *Packet) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *Packet) GetDocTitle() string {
	if x != nil {
		return x.DocTitle
	}
	return ""
}

func (x *Packet) GetDeliveryStatus() PacketDeliveryStatus {
	if x != nil {
		return x.DeliveryStatus
	}
	return PacketDeliveryStatus_InDelivery
}

var File_engine_vector_space_search_service_proto protoreflect.FileDescriptor

var file_engine_vector_space_search_service_proto_rawDesc = []byte{
	0x0a, 0x28, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2d, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2d,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x2d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2e, 0x61, 0x6d, 0x61, 0x7a,
	0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x76,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0xdc, 0x02, 0x0a, 0x06, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x5b, 0x0a, 0x0b, 0x77, 0x65, 0x62, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3a, 0x2e, 0x61, 0x6d, 0x61,
	0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f,
	0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x57, 0x65, 0x62, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x77, 0x65, 0x62, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x52, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x37, 0x2e, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68,
	0x6f, 0x77, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x6f, 0x63, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x64,
	0x6f, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x63, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x64, 0x6f, 0x63, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x6f, 0x63, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x6d, 0x0a, 0x0f, 0x64, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x44, 0x2e, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f,
	0x77, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0e, 0x64, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x18, 0x0a, 0x0a, 0x57, 0x65, 0x62,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x4f, 0x46, 0x52, 0x50,
	0x43, 0x10, 0x00, 0x2a, 0x23, 0x0a, 0x07, 0x44, 0x6f, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x48, 0x54, 0x4d, 0x4c, 0x44, 0x6f, 0x63, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x54,
	0x65, 0x78, 0x74, 0x44, 0x6f, 0x63, 0x10, 0x01, 0x2a, 0x36, 0x0a, 0x14, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x6e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x10, 0x00,
	0x12, 0x0e, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x4f, 0x66, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x10, 0x01,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_engine_vector_space_search_service_proto_rawDescOnce sync.Once
	file_engine_vector_space_search_service_proto_rawDescData = file_engine_vector_space_search_service_proto_rawDesc
)

func file_engine_vector_space_search_service_proto_rawDescGZIP() []byte {
	file_engine_vector_space_search_service_proto_rawDescOnce.Do(func() {
		file_engine_vector_space_search_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_engine_vector_space_search_service_proto_rawDescData)
	})
	return file_engine_vector_space_search_service_proto_rawDescData
}

var file_engine_vector_space_search_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_engine_vector_space_search_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_engine_vector_space_search_service_proto_goTypes = []interface{}{
	(WebStation)(0),           // 0: amazingchow.engine_vector_space_search_service.WebStation
	(DocType)(0),              // 1: amazingchow.engine_vector_space_search_service.DocType
	(PacketDeliveryStatus)(0), // 2: amazingchow.engine_vector_space_search_service.PacketDeliveryStatus
	(*Packet)(nil),            // 3: amazingchow.engine_vector_space_search_service.Packet
}
var file_engine_vector_space_search_service_proto_depIdxs = []int32{
	0, // 0: amazingchow.engine_vector_space_search_service.Packet.web_station:type_name -> amazingchow.engine_vector_space_search_service.WebStation
	1, // 1: amazingchow.engine_vector_space_search_service.Packet.doc_type:type_name -> amazingchow.engine_vector_space_search_service.DocType
	2, // 2: amazingchow.engine_vector_space_search_service.Packet.delivery_status:type_name -> amazingchow.engine_vector_space_search_service.PacketDeliveryStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_engine_vector_space_search_service_proto_init() }
func file_engine_vector_space_search_service_proto_init() {
	if File_engine_vector_space_search_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_engine_vector_space_search_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_engine_vector_space_search_service_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_engine_vector_space_search_service_proto_goTypes,
		DependencyIndexes: file_engine_vector_space_search_service_proto_depIdxs,
		EnumInfos:         file_engine_vector_space_search_service_proto_enumTypes,
		MessageInfos:      file_engine_vector_space_search_service_proto_msgTypes,
	}.Build()
	File_engine_vector_space_search_service_proto = out.File
	file_engine_vector_space_search_service_proto_rawDesc = nil
	file_engine_vector_space_search_service_proto_goTypes = nil
	file_engine_vector_space_search_service_proto_depIdxs = nil
}
