// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: engine-vector-space-search-service.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WebStation int32

const (
	// 中华人民共和国财政部网站
	WebStation_MOFRPC WebStation = 0
)

// Enum value maps for WebStation.
var (
	WebStation_name = map[int32]string{
		0: "MOFRPC",
	}
	WebStation_value = map[string]int32{
		"MOFRPC": 0,
	}
)

func (x WebStation) Enum() *WebStation {
	p := new(WebStation)
	*p = x
	return p
}

func (x WebStation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebStation) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_vector_space_search_service_proto_enumTypes[0].Descriptor()
}

func (WebStation) Type() protoreflect.EnumType {
	return &file_engine_vector_space_search_service_proto_enumTypes[0]
}

func (x WebStation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebStation.Descriptor instead.
func (WebStation) EnumDescriptor() ([]byte, []int) {
	return file_engine_vector_space_search_service_proto_rawDescGZIP(), []int{0}
}

type FileType int32

const (
	// HTML格式文件
	FileType_HTMLFile FileType = 0
	// TXT格式文件
	FileType_TextFile FileType = 1
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "HTMLFile",
		1: "TextFile",
	}
	FileType_value = map[string]int32{
		"HTMLFile": 0,
		"TextFile": 1,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_vector_space_search_service_proto_enumTypes[1].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_engine_vector_space_search_service_proto_enumTypes[1]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_engine_vector_space_search_service_proto_rawDescGZIP(), []int{1}
}

// 传输数据包.
type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WebStation WebStation `protobuf:"varint,1,opt,name=web_station,json=webStation,proto3,enum=amazingchow.engine_vector_space_search_service.WebStation" json:"web_station,omitempty"`
	FileType   FileType   `protobuf:"varint,2,opt,name=file_type,json=fileType,proto3,enum=amazingchow.engine_vector_space_search_service.FileType" json:"file_type,omitempty"`
	FileTitle  string     `protobuf:"bytes,3,opt,name=file_title,json=fileTitle,proto3" json:"file_title,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_vector_space_search_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_engine_vector_space_search_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_engine_vector_space_search_service_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetWebStation() WebStation {
	if x != nil {
		return x.WebStation
	}
	return WebStation_MOFRPC
}

func (x *Packet) GetFileType() FileType {
	if x != nil {
		return x.FileType
	}
	return FileType_HTMLFile
}

func (x *Packet) GetFileTitle() string {
	if x != nil {
		return x.FileTitle
	}
	return ""
}

var File_engine_vector_space_search_service_proto protoreflect.FileDescriptor

var file_engine_vector_space_search_service_proto_rawDesc = []byte{
	0x0a, 0x28, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2d, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2d,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x2d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2e, 0x61, 0x6d, 0x61, 0x7a,
	0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x76,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0xdb, 0x01, 0x0a, 0x06, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x5b, 0x0a, 0x0b, 0x77, 0x65, 0x62, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3a, 0x2e, 0x61, 0x6d, 0x61,
	0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f,
	0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x57, 0x65, 0x62, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x77, 0x65, 0x62, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x55, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x38, 0x2e, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63,
	0x68, 0x6f, 0x77, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x76, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x2a, 0x18, 0x0a, 0x0a, 0x57, 0x65, 0x62, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x4f, 0x46, 0x52, 0x50, 0x43,
	0x10, 0x00, 0x2a, 0x26, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c,
	0x0a, 0x08, 0x48, 0x54, 0x4d, 0x4c, 0x46, 0x69, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x54, 0x65, 0x78, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x10, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_engine_vector_space_search_service_proto_rawDescOnce sync.Once
	file_engine_vector_space_search_service_proto_rawDescData = file_engine_vector_space_search_service_proto_rawDesc
)

func file_engine_vector_space_search_service_proto_rawDescGZIP() []byte {
	file_engine_vector_space_search_service_proto_rawDescOnce.Do(func() {
		file_engine_vector_space_search_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_engine_vector_space_search_service_proto_rawDescData)
	})
	return file_engine_vector_space_search_service_proto_rawDescData
}

var file_engine_vector_space_search_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_engine_vector_space_search_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_engine_vector_space_search_service_proto_goTypes = []interface{}{
	(WebStation)(0), // 0: amazingchow.engine_vector_space_search_service.WebStation
	(FileType)(0),   // 1: amazingchow.engine_vector_space_search_service.FileType
	(*Packet)(nil),  // 2: amazingchow.engine_vector_space_search_service.Packet
}
var file_engine_vector_space_search_service_proto_depIdxs = []int32{
	0, // 0: amazingchow.engine_vector_space_search_service.Packet.web_station:type_name -> amazingchow.engine_vector_space_search_service.WebStation
	1, // 1: amazingchow.engine_vector_space_search_service.Packet.file_type:type_name -> amazingchow.engine_vector_space_search_service.FileType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_engine_vector_space_search_service_proto_init() }
func file_engine_vector_space_search_service_proto_init() {
	if File_engine_vector_space_search_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_engine_vector_space_search_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_engine_vector_space_search_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_engine_vector_space_search_service_proto_goTypes,
		DependencyIndexes: file_engine_vector_space_search_service_proto_depIdxs,
		EnumInfos:         file_engine_vector_space_search_service_proto_enumTypes,
		MessageInfos:      file_engine_vector_space_search_service_proto_msgTypes,
	}.Build()
	File_engine_vector_space_search_service_proto = out.File
	file_engine_vector_space_search_service_proto_rawDesc = nil
	file_engine_vector_space_search_service_proto_goTypes = nil
	file_engine_vector_space_search_service_proto_depIdxs = nil
}
